name: navigation

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  home:
    path: ../features/home

  settings:
    path: ../features/settings

  character:
    path: ../features/character

  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  auto_route_generator: ^9.0.0

