name: character

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core

  core_ui:
    path: ../../core_ui

  domain:
    path: ../../domain

  navigation:
    path: ../../navigation

  #UI
  paginated_list: ^1.2.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  auto_route_generator: ^9.0.0