name: core

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Localization
  easy_localization: ^3.0.7

  #Storages
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1

  #IoC
  get_it: ^8.0.2

  #State management
  flutter_bloc: ^8.1.4

  #Network
  observe_internet_connectivity: ^1.0.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8

flutter:
  assets:
    - languages/
