name: domain

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  data:
    path: ../data

  core_ui:
    path: ../core_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8