name: settings

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8